version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: frontends/web/Dockerfile
      args:
        buildno: 1
  backendservice:
    build:
      context: ./
      dockerfile: frontends/services/svcname/Dockerfile
  
